apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: react-scan-pipelinerun
spec:
  params: 
    - name: "github-repo-revision"
      value: "main"
    - name: "github-repo-url"
      value: "https://github.com/shaneboulden/chat-client.git"
    - name: "context-dir"
      value: "/"
    - name: "image-name"
      value: "quay.io/jrickard0/chat-client:latest"
    - name: "is-name"
      value: "chat-client"
    - name: "acs-image"
      value: "quay.io/jrickard0/chat-client:latest"
    - name: "acs-scan-api"
      value: "central-rhacs-operator.apps.jrickard-dsohub.blueprints.rhecoeng.com"
  pipelineRef:
    name: build-scan-and-deploy
  podTemplate:
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc
  serviceAccountName: pipeline
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc
