apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: containers-pvc2
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
