kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: devsecops
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: devsecops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: devsecops
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: devsecops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:image-puller-dev
  namespace: devsecops
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devsecops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
